/* three.js ships as an ES module only. A module cannot be imported from a
   `file://` page — the origin is opaque, so the browser refuses it — and this
   repo's rule is that everything keeps working off the disk with the network
   off. So the module is wrapped into a plain script that hangs THREE on the
   window, which a classic <script> tag can load from anywhere.

   The transform is mechanical and total: the file has exactly one `export {…}`
   statement, no `export default`, and no imports of its own. If a future
   three.js breaks any of those, this refuses to run rather than emitting
   something subtly wrong.

   Run:  node tools/buildthree.js                                           */

const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, '..', 'game', 'vendor');
const src = fs.readFileSync(path.join(dir, 'three.module.js'), 'utf8');

const lines = src.split('\n');
const exportLines = lines
  .map((l, i) => ({ l: l, i: i }))
  .filter(o => /^\s*export\s/.test(o.l));

if (exportLines.length !== 1) {
  console.error('expected exactly one export statement, found ' + exportLines.length);
  process.exit(1);
}
if (/^\s*import\s|^\s*export\s+default/m.test(src)) {
  console.error('the module imports something, or has a default export — not handled');
  process.exit(1);
}

const stmt = exportLines[0].l;
const inner = stmt.replace(/^\s*export\s*\{/, '').replace(/\}\s*;?\s*$/, '');
const names = inner.split(',').map(s => s.trim()).filter(Boolean);

const aliased = names.filter(n => /\s+as\s+/.test(n));
if (aliased.length) {
  console.error('renamed exports are not handled: ' + aliased.slice(0, 3).join(', '));
  process.exit(1);
}
if (!names.every(n => /^[A-Za-z_$][\w$]*$/.test(n))) {
  console.error('an export name is not a plain identifier');
  process.exit(1);
}

const body = lines.slice(0, exportLines[0].i).join('\n');
const out =
  '/* three.js r' + (src.match(/REVISION\s*=\s*'([^']+)'/) || [, '?'])[1] +
  ', MIT, wrapped as a classic script by tools/buildthree.js.\n' +
  '   Do not edit this file — edit three.module.js and run the tool. */\n' +
  '(function () {\n' +
  body +
  '\n  window.THREE = {\n    ' +
  names.map(n => n + ': ' + n).join(',\n    ') +
  '\n  };\n})();\n';

fs.writeFileSync(path.join(dir, 'three.global.js'), out);
console.log('wrote game/vendor/three.global.js — ' + names.length + ' exports, ' +
            (out.length / 1024 / 1024).toFixed(2) + ' MB');
