/* GLTFLoader fetches, and fetch refuses a `file://` URL — so a page opened off
   a disc can load three.js and the rules but not a single model. Rather than
   give up opening the game from the filesystem, the models are baked into one
   script as base64 and handed to the loader's parse() directly.

   Run after adding or removing anything in game/assets/kit/:
     node tools/buildkit.js                                                 */

const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, '..', 'game', 'assets', 'kit');
const files = fs.readdirSync(dir).filter(f => f.endsWith('.glb')).sort();

if (!files.length) {
  console.error('no .glb files in game/assets/kit');
  process.exit(1);
}

const parts = files.map(function (f) {
  const b64 = fs.readFileSync(path.join(dir, f)).toString('base64');
  return '  ' + JSON.stringify(f.replace(/\.glb$/, '')) + ': "' + b64 + '"';
});

const out =
  '/* The scenery, baked in. Kenney Space Kit, CC0 — see assets/kit/LICENSE-kenney.txt.\n' +
  '   Generated by tools/buildkit.js from assets/kit/*.glb; do not edit by hand.\n' +
  '   They live here rather than as loose files because GLTFLoader fetches, and\n' +
  '   fetch will not touch a file:// URL. */\n' +
  'window.KIT_DATA = {\n' + parts.join(',\n') + '\n};\n';

fs.writeFileSync(path.join(__dirname, '..', 'game', 'assets', 'kit.js'), out);
console.log('wrote game/assets/kit.js — ' + files.length + ' models, ' +
            (out.length / 1024 / 1024).toFixed(2) + ' MB');
